config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
 root 'home#index'
 resources :homes
 resources :events
 resources :users
 resources :attendances
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
  validates :attendee_id, uniqueness: { scope: :attended_event_id, message: 'User is already attending this event' }
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, foreign_key: 'creator_id', class_name: 'User'
  has_many :attendances, foreign_key: 'attended_event_id'
  has_many :attendees, through: :attendances

  validates :title, presence: true, length: { minimum: 2 }
  validates :description, presence: true, length: { in: 5..100 }

  scope :upcoming, -> { where('start_time >= ?', Time.now) }
  scope :previous, -> { where('start_time < ?', Time.now) }
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 16 }
  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :attendances, foreign_key: 'attendee_id'
  has_many :attended_events, through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def new
    @attendance = Attendance.new
    @event = Event.find(session[:current_event])
  end

  def create
    @attendance = Attendance.new
    @attendance.attendee = current_user
    @attendance.attended_event_id = session[:current_event]
    if @attendance.save
      flash[:success] = "#{current_user.name} will attend to this event!"
      redirect_to @attendance
    else
      flash[:danger] = 'Something went wrong, you might be already assisting event!'
      @event = Event.find(session[:current_event])
      render 'new'
    end
  end

  def show
    @attenance = Attendance.find(params[:id])
  end

  private

  def attendance_params
    params.permit(:attended_event_id, :attendee_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  def index
    @events = Event.all.order('created_at DESC')
    @future_events = Event.upcoming
    @previous_events = Event.previous
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event
      flash[:success] = 'Event was created successfully!'
    else
      flash[:danger] = "Event wasn't created! Try again!"
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    session[:current_event] = @event.id
  end

  private

  def event_params
    params.require(:event).permit(:start_time, :creator_id, :end_time, :title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update
    params.require(:user).permit(:name, :username, :password, :password_confirmation, :current_password, :avatar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user = current_user
    @upcoming_events = current_user.attended_events.upcoming
    @past_events = current_user.attended_events.previous
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def if_user_logged_in
    if user_signed_in?
      (link_to 'Log Out', destroy_user_session_path, method: :delete, data: { confirm: 'Are You Sure?' },
                                                     class: 'btn pink') +
        (link_to current_user.name, user_path(current_user), class: 'btn pink')
    else
      (link_to 'Log In', new_user_session_path, class: 'btn pink mx-3') +
        (link_to 'Sign Up', new_user_registration_path, class: 'btn pink')
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/show.html.erb
<h1>You Are Attending To This Event</h1><br>
<%= link_to 'Back', events_path, class:'btn btn-warning' %>

app/views/events/_events_cta.html.erb
<div class="container my-4">
<%= image_tag 's.svg' %>
<h1>It looks like you haven't scheduled a session yet</h1>
</div>

<%= link_to 'Create New Event', new_event_path, class:'btn btn-success' %>

app/views/events/_events_landing.html.erb
<div class="container">
	<h1>
		Hello <%= current_user.name %> this is  list of all past events 
	</h1>
	<% @previous_events.each do |e| %>
	<%= link_to e.title, e %><br>
	<% end %>
	<h2>This is the list of upcoming events:</h2>
	<% @future_events.each do |e| %>
	<%= link_to e.title, e %><br>
	<% end %>
	<%= link_to 'Create New Event', new_event_path, class:'btn btn-success' %>
	<%= link_to 'Back To Home Page', root_path, class:'btn btn-dark' %>
</div>

app/views/events/index.html.erb
<div class="container">
	<!-- if user has any meetings to show -->
	<% unless current_user.created_events.any? %>
<%= render 'events_cta' %>
	<% else %>
	<!-- here i am passing variable from index method from the controller  -->
<%= render 'events_landing', events: @events %>
	<% end %>
</div>

app/views/events/new.html.erb
<%= simple_form_for @event do |f| %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.input :start_time %>
<%= f.input :end_time %>
<%= f.submit %><br><br>
<%= link_to 'Cancel', events_path, class:'btn btn-danger' %>
<% end %>

app/views/events/show.html.erb
<div class="position-relative">
 <div class="card" style="width: 22rem; margin:5% auto;">
  <div class="card-body">
    <h5 class="card-title"><%= @event.title %></h5>
    <p class="card-text"><%= @event.description %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Start Time:
		<%= @event.start_time %></li>
    <li class="list-group-item">End Time:
		<%= @event.end_time %></li>
     <li class="list-group-item">
      <p>Event created by: <%= @event.creator.name %></p>
     </li>
  </ul>
  <div class="card-body" style="height: 73px;">
    <a href="#" class="card-link"><%= link_to "Back", events_path, class:'btn btn-secondary' %></a>
    <a href="#" class="card-link"><%= link_to 'Edit', edit_event_path, class:'btn btn-secondary' %></a>
   <%= form_with model: @attendance, method: :post, url: attendances_path do |f| %><br>
   <%= f.submit 'I will assist', class:'btn btn-success as' %><br>
    <% end %>
  </div>
</div>
<div class="info-dej">
<h4>This is the list of users who are attending to the event:</h4>
<% @event.attendees.each do |r| %><br>
<%= link_to r.name, r, class:'btn btn-secondary' %><br>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="#">Private Events</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <%= link_to 'Dashboard', events_path, class:'btn btn-success' %>
        </li>
      </ul>
    
    </div>
      <div class="d-flex float-end">
        <%= if_user_logged_in %>
      </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="container">
<h3>Welcome <%= current_user.name %>, this is the list of past events you attended:</h3>
<%  @past_events.each do |r| %>
<%= link_to r.title, r %><br>
	<% end %>

<h3><%= current_user.name %> this is the list of future events you are attending:</h3>
<% @upcoming_events.each do |r| %>
<%= link_to r.title, r %><br>
	<% end %><br>
</div>


<div class="container">
<h3>
 <%= current_user.name %>, This Is The List Of Events You've Created 
</h3>
<% current_user.created_events.each do |s| %>
<%= link_to s.title, s %><br>
<% end %>
<%= link_to "Back To Home Page", root_path, class:'btn btn-warning' %>
</div>